### PR TITLE
add assembly view

### PR DESCRIPTION
**Pull request by techmannih**
add assembly view
/claim #62 

https://github.com/user-attachments/assets/c4053153-a46c-4a3a-a72e-e38da6ba42ee

### CODE REVIEW

**Review by ShiboSoftwareDev — CHANGES_REQUESTED** [review]
fix typecheck

**Review by seveibar — CHANGES_REQUESTED** [review]
nice work but should be part of dropdown, we don't have enough header space

**Comment by seveibar** [comment]
@techmannih the assembly viewer is now published

**Review by ShiboSoftwareDev — APPROVED** [review]
@seveibar the text looks weird but I guess this is it's own issue
image

**Review by seveibar — APPROVED** [review]

**Comment by seveibar** [comment]
@techmannih you can resolve merge conflicts following this guide https://github.com/tscircuit/handbook/blob/main/guides/basics/learn-git.md#resolving-bunlockb-conflicts

**Pull request merged**
